
import {
  Activity, AlarmClockCheck, AlarmClockOff, AlignCenter, AlignHorizontalDistributeCenter, AlignHorizontalDistributeEnd,
  AlignHorizontalDistributeStart, AlignHorizontalSpaceAround, AlignHorizontalSpaceBetween, AlignJustify, AlignLeft,
  AlignRight, AlignVerticalDistributeCenter, AlignVerticalDistributeEnd, AlignVerticalDistributeStart,
  AlignVerticalSpaceAround, AlignVerticalSpaceBetween, Ampersand, Archive, ArrowBigDown, ArrowBigLeft, ArrowBigRight, ArrowBigUp,
  ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Asterisk, AtSign, Award, Axe, BadgeCheck, BarChart2, Bell, Bike, Bold, Bookmark, Bot,
  Box, Briefcase, Brush, Building, Bus, Calculator, Calendar, Camera, Car, Check, CheckCircle2, ChevronDown, ChevronLeft,
  ChevronRight, ChevronUp, ChevronsDown, ChevronsLeft, ChevronsRight, ChevronsUp, Chrome, Clapperboard, Clipboard, Cloud,
  CloudCog, CloudDrizzle, CloudFog, CloudHail, CloudLightning, CloudMoon, CloudMoonRain, CloudRain, CloudRainWind, CloudSnow,
  CloudSun, CloudSunRain, CloudUpload, Code, Codepen, Coffee, Cog, Coins, Compass, Copy, Cpu, CreditCard, Crop, Crown, Database,
  Delete, Dna, DollarSign, Download, Dribbble, Droplet, Edit, ExternalLink, Eye, Facebook, Feather, Figma, File, FileArchive,
  FileAudio, FileBadge, FileCheck, FileCode, FileDigit, FileDown, FileEdit, FileHeart, FileImage, FileInput, FileJson, FileKey,
  FileLock, FileMinus, FilePlus, FileQuestion, FileScan, FileSearch, FileSymlink, FileText, FileUp, FileVideo, FileWarning,
  FileX, Film, Filter, Flag, Flame, FlaskConical, FlaskRound, Folder, FolderArchive, FolderCheck, FolderClock, FolderClosed,
  FolderCog, FolderDown, FolderEdit, FolderGit, FolderHeart, FolderInput, FolderKey, FolderLock, FolderMinus, FolderOpen,
  FolderPlus, FolderRoot, FolderSearch, FolderSymlink, FolderSync, FolderTree, FolderUp, FolderX, Framer, Frown, Gamepad, Gem,
  Ghost, Gift, GitBranch, GitCommit, GitFork, GitMerge, GitPullRequest, Github, Gitlab, GlassWater, Globe, Grab, Grid, Hammer,
  Hand, HardDrive, HardHat, Hash, Haze, Heading, Heart, HelpCircle, Highlighter, Home, Image, Inbox, Indent, Info, Instagram,
  Italic, Key, Keyboard, Landmark, Languages, Laptop, Lasso, Laugh, Layers, Layout, LayoutDashboard, LayoutGrid, LayoutList,
  LifeBuoy, Lightbulb, Link, Linkedin, List, ListChecks, ListEnd, ListMinus, ListMusic, ListOrdered, ListPlus, ListStart,
  ListVideo, ListX, Loader, Lock, LogIn, LogOut, Mail, Map, MapPin, Maximize, Menu, MessageCircle, MessageSquare, Mic, Mic2,
  Minus, Monitor, Moon, MoreHorizontal, MoreVertical, MousePointer, Move, Music, Navigation, Newspaper, Package, Paintbrush,
  Palette, Paperclip, ParkingCircle, Pause, Pen, Pencil, Percent, PersonStanding, Phone, PictureInPicture, PieChart, Pilcrow,
  Pin, Play, Plug, Plus, Pocket, Podcast, Pointer, Power, Printer, QrCode, Quote, Redo, RefreshCcw, RefreshCw, Reply, Rocket,
  RotateCcw, RotateCw, Rss, Ruler, Save, Scale, Scissors, ScreenShare, Search, Send, SeparatorHorizontal, Server, Settings,
  Settings2, Share, Share2, Sheet, Shield, ShieldCheck, ShieldClose, ShieldOff, Shirt, ShoppingBag, ShoppingCart, Siren, Slash,
  Slice, Smartphone, Smile, Speaker, Star, Strikethrough, Sun, Sunrise, Sunset, Tablet, Tag, Target, Tent, Terminal, ThumbsDown,
  ThumbsUp, ToggleLeft, ToggleRight, Tool, Trash, Trash2, TrendingDown, TrendingUp, Triangle, Truck, Tv, Twitch, Twitter, Type,
  Underline, Undo, UnfoldHorizontal, UnfoldVertical, Unlink, Upload, User, UserCheck, UserCog, UserMinus, UserPlus, UserX, Users,
  Video, Voicemail, Volume, Volume1, Volume2, VolumeX, Wallet, Watch, Webcam, Wifi, Wind, Workflow, WrapText, X, Youtube, Zap
} from 'lucide-react';
import * as React from 'react';

// Ícone do WhatsApp
const WhatsappIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    {...props}
  >
    <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
  </svg>
);

// Ícone do Telegram
const TelegramIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    {...props}
  >
    <path d="M22 2 11 13" />
    <path d="m22 2-7 20-4-9-9-4 20-7z" />
  </svg>
);

// Ícone para Vendedor/Gestão
const SellerIcon = () => <Users className="h-6 w-6 text-primary" />;

// Ícone para Checkout
const CheckoutIcon = () => <ShoppingCart className="h-6 w-6 text-primary" />;

// Ícone para Catálogo
const CatalogIcon = () => <Settings className="h-6 w-6 text-primary" />;

export interface IconDefinition {
  component: React.ElementType;
  label: string;
}

export const ctaIconsMap: Record<string, IconDefinition> = {
  arrowRight: { component: ArrowRight, label: 'Seta' },
  whatsapp: { component: WhatsappIcon, label: 'WhatsApp' },
  telegram: { component: TelegramIcon, label: 'Telegram' },
  send: { component: Send, label: 'Enviar' },
  mail: { component: Mail, label: 'Email' },
  phone: { component: Phone, label: 'Telefone' },
  rocket: { component: Rocket, label: 'Começar' },
  none: { component: () => null, label: 'Nenhum' },
};

export const allIconsMap: Record<string, IconDefinition> = {
  activity: { component: Activity, label: 'Activity' },
  alarmClockCheck: { component: AlarmClockCheck, label: 'Alarm Clock Check' },
  alarmClockOff: { component: AlarmClockOff, label: 'Alarm Clock Off' },
  alignCenter: { component: AlignCenter, label: 'Align Center' },
  alignHorizontalDistributeCenter: { component: AlignHorizontalDistributeCenter, label: 'Align Horizontal Distribute Center' },
  alignHorizontalDistributeEnd: { component: AlignHorizontalDistributeEnd, label: 'Align Horizontal Distribute End' },
  alignHorizontalDistributeStart: { component: AlignHorizontalDistributeStart, label: 'Align Horizontal Distribute Start' },
  alignHorizontalSpaceAround: { component: AlignHorizontalSpaceAround, label: 'Align Horizontal Space Around' },
  alignHorizontalSpaceBetween: { component: AlignHorizontalSpaceBetween, label: 'Align Horizontal Space Between' },
  alignJustify: { component: AlignJustify, label: 'Align Justify' },
  alignLeft: { component: AlignLeft, label: 'Align Left' },
  alignRight: { component: AlignRight, label: 'Align Right' },
  alignVerticalDistributeCenter: { component: AlignVerticalDistributeCenter, label: 'Align Vertical Distribute Center' },
  alignVerticalDistributeEnd: { component: AlignVerticalDistributeEnd, label: 'Align Vertical Distribute End' },
  alignVerticalDistributeStart: { component: AlignVerticalDistributeStart, label: 'Align Vertical Distribute Start' },
  alignVerticalSpaceAround: { component: AlignVerticalSpaceAround, label: 'Align Vertical Space Around' },
  alignVerticalSpaceBetween: { component: AlignVerticalSpaceBetween, label: 'Align Vertical Space Between' },
  ampersand: { component: Ampersand, label: 'Ampersand' },
  archive: { component: Archive, label: 'Archive' },
  arrowBigDown: { component: ArrowBigDown, label: 'Arrow Big Down' },
  arrowBigLeft: { component: ArrowBigLeft, label: 'Arrow Big Left' },
  arrowBigRight: { component: ArrowBigRight, label: 'Arrow Big Right' },
  arrowBigUp: { component: ArrowBigUp, label: 'Arrow Big Up' },
  arrowDown: { component: ArrowDown, label: 'Arrow Down' },
  arrowLeft: { component: ArrowLeft, label: 'Arrow Left' },
  arrowRight: { component: ArrowRight, label: 'Arrow Right' },
  arrowUp: { component: ArrowUp, label: 'Arrow Up' },
  asterisk: { component: Asterisk, label: 'Asterisk' },
  atSign: { component: AtSign, label: 'At Sign' },
  award: { component: Award, label: 'Award' },
  axe: { component: Axe, label: 'Axe' },
  badgeCheck: { component: BadgeCheck, label: 'Badge Check' },
  barChart2: { component: BarChart2, label: 'Bar Chart' },
  bell: { component: Bell, label: 'Bell' },
  bike: { component: Bike, label: 'Bike' },
  bold: { component: Bold, label: 'Bold' },
  bookmark: { component: Bookmark, label: 'Bookmark' },
  bot: { component: Bot, label: 'Bot' },
  box: { component: Box, label: 'Box' },
  briefcase: { component: Briefcase, label: 'Briefcase' },
  brush: { component: Brush, label: 'Brush' },
  building: { component: Building, label: 'Building' },
  bus: { component: Bus, label: 'Bus' },
  calculator: { component: Calculator, label: 'Calculator' },
  calendar: { component: Calendar, label: 'Calendar' },
  camera: { component: Camera, label: 'Camera' },
  car: { component: Car, label: 'Car' },
  check: { component: Check, label: 'Check' },
  checkCircle2: { component: CheckCircle2, label: 'Check Circle' },
  chevronDown: { component: ChevronDown, label: 'Chevron Down' },
  chevronLeft: { component: ChevronLeft, label: 'Chevron Left' },
  chevronRight: { component: ChevronRight, label: 'Chevron Right' },
  chevronUp: { component: ChevronUp, label: 'Chevron Up' },
  chevronsDown: { component: ChevronsDown, label: 'Chevrons Down' },
  chevronsLeft: { component: ChevronsLeft, label: 'Chevrons Left' },
  chevronsRight: { component: ChevronsRight, label: 'Chevrons Right' },
  chevronsUp: { component: ChevronsUp, label: 'Chevrons Up' },
  chrome: { component: Chrome, label: 'Chrome' },
  clapperboard: { component: Clapperboard, label: 'Clapperboard' },
  clipboard: { component: Clipboard, label: 'Clipboard' },
  cloud: { component: Cloud, label: 'Cloud' },
  cloudCog: { component: CloudCog, label: 'Cloud Cog' },
  cloudDrizzle: { component: CloudDrizzle, label: 'Cloud Drizzle' },
  cloudFog: { component: CloudFog, label: 'Cloud Fog' },
  cloudHail: { component: CloudHail, label: 'Cloud Hail' },
  cloudLightning: { component: CloudLightning, label: 'Cloud Lightning' },
  cloudMoon: { component: CloudMoon, label: 'Cloud Moon' },
  cloudMoonRain: { component: CloudMoonRain, label: 'Cloud Moon Rain' },
  cloudRain: { component: CloudRain, label: 'Cloud Rain' },
  cloudRainWind: { component: CloudRainWind, label: 'Cloud Rain Wind' },
  cloudSnow: { component: CloudSnow, label: 'Cloud Snow' },
  cloudSun: { component: CloudSun, label: 'Cloud Sun' },
  cloudSunRain: { component: CloudSunRain, label: 'Cloud Sun Rain' },
  cloudUpload: { component: CloudUpload, label: 'Cloud Upload' },
  code: { component: Code, label: 'Code' },
  codepen: { component: Codepen, label: 'Codepen' },
  coffee: { component: Coffee, label: 'Coffee' },
  cog: { component: Cog, label: 'Cog' },
  coins: { component: Coins, label: 'Coins' },
  compass: { component: Compass, label: 'Compass' },
  copy: { component: Copy, label: 'Copy' },
  cpu: { component: Cpu, label: 'Cpu' },
  creditCard: { component: CreditCard, label: 'Credit Card' },
  crop: { component: Crop, label: 'Crop' },
  crown: { component: Crown, label: 'Crown' },
  database: { component: Database, label: 'Database' },
  delete: { component: Delete, label: 'Delete' },
  dna: { component: Dna, label: 'Dna' },
  dollarSign: { component: DollarSign, label: 'Dollar Sign' },
  download: { component: Download, label: 'Download' },
  dribbble: { component: Dribbble, label: 'Dribbble' },
  droplet: { component: Droplet, label: 'Droplet' },
  edit: { component: Edit, label: 'Edit' },
  externalLink: { component: ExternalLink, label: 'External Link' },
  eye: { component: Eye, label: 'Eye' },
  facebook: { component: Facebook, label: 'Facebook' },
  feather: { component: Feather, label: 'Feather' },
  figma: { component: Figma, label: 'Figma' },
  file: { component: File, label: 'File' },
  fileArchive: { component: FileArchive, label: 'File Archive' },
  fileAudio: { component: FileAudio, label: 'File Audio' },
  fileBadge: { component: FileBadge, label: 'File Badge' },
  fileCheck: { component: FileCheck, label: 'File Check' },
  fileCode: { component: FileCode, label: 'File Code' },
  fileDigit: { component: FileDigit, label: 'File Digit' },
  fileDown: { component: FileDown, label: 'File Down' },
  fileEdit: { component: FileEdit, label: 'File Edit' },
  fileHeart: { component: FileHeart, label: 'File Heart' },
  fileImage: { component: FileImage, label: 'File Image' },
  fileInput: { component: FileInput, label: 'File Input' },
  fileJson: { component: FileJson, label: 'File Json' },
  fileKey: { component: FileKey, label: 'File Key' },
  fileLock: { component: FileLock, label: 'File Lock' },
  fileMinus: { component: FileMinus, label: 'File Minus' },
  filePlus: { component: FilePlus, label: 'File Plus' },
  fileQuestion: { component: FileQuestion, label: 'File Question' },
  fileScan: { component: FileScan, label: 'File Scan' },
  fileSearch: { component: FileSearch, label: 'File Search' },
  fileSymlink: { component: FileSymlink, label: 'File Symlink' },
  fileText: { component: FileText, label: 'File Text' },
  fileUp: { component: FileUp, label: 'File Up' },
  fileVideo: { component: FileVideo, label: 'File Video' },
  fileWarning: { component: FileWarning, label: 'File Warning' },
  fileX: { component: FileX, label: 'File X' },
  film: { component: Film, label: 'Film' },
  filter: { component: Filter, label: 'Filter' },
  flag: { component: Flag, label: 'Flag' },
  flame: { component: Flame, label: 'Flame' },
  flaskConical: { component: FlaskConical, label: 'Flask Conical' },
  flaskRound: { component: FlaskRound, label: 'Flask Round' },
  folder: { component: Folder, label: 'Folder' },
  folderArchive: { component: FolderArchive, label: 'Folder Archive' },
  folderCheck: { component: FolderCheck, label: 'Folder Check' },
  folderClock: { component: FolderClock, label: 'Folder Clock' },
  folderClosed: { component: FolderClosed, label: 'Folder Closed' },
  folderCog: { component: FolderCog, label: 'Folder Cog' },
  folderDown: { component: FolderDown, label: 'Folder Down' },
  folderEdit: { component: FolderEdit, label: 'Folder Edit' },
  folderGit: { component: FolderGit, label: 'Folder Git' },
  folderHeart: { component: FolderHeart, label: 'Folder Heart' },
  folderInput: { component: FolderInput, label: 'Folder Input' },
  folderKey: { component: FolderKey, label: 'Folder Key' },
  folderLock: { component: FolderLock, label: 'Folder Lock' },
  folderMinus: { component: FolderMinus, label: 'Folder Minus' },
  folderOpen: { component: FolderOpen, label: 'Folder Open' },
  folderPlus: { component: FolderPlus, label: 'Folder Plus' },
  folderRoot: { component: FolderRoot, label: 'Folder Root' },
  folderSearch: { component: FolderSearch, label: 'Folder Search' },
  folderSymlink: { component: FolderSymlink, label: 'Folder Symlink' },
  folderSync: { component: FolderSync, label: 'Folder Sync' },
  folderTree: { component: FolderTree, label: 'Folder Tree' },
  folderUp: { component: FolderUp, label: 'Folder Up' },
  folderX: { component: FolderX, label: 'Folder X' },
  framer: { component: Framer, label: 'Framer' },
  frown: { component: Frown, label: 'Frown' },
  gamepad: { component: Gamepad, label: 'Gamepad' },
  gem: { component: Gem, label: 'Gem' },
  ghost: { component: Ghost, label: 'Ghost' },
  gift: { component: Gift, label: 'Gift' },
  gitBranch: { component: GitBranch, label: 'Git Branch' },
  gitCommit: { component: GitCommit, label: 'Git Commit' },
  gitFork: { component: GitFork, label: 'Git Fork' },
  gitMerge: { component: GitMerge, label: 'Git Merge' },
  gitPullRequest: { component: GitPullRequest, label: 'Git Pull Request' },
  github: { component: Github, label: 'Github' },
  gitlab: { component: Gitlab, label: 'Gitlab' },
  glassWater: { component: GlassWater, label: 'Glass Water' },
  globe: { component: Globe, label: 'Globe' },
  grab: { component: Grab, label: 'Grab' },
  grid: { component: Grid, label: 'Grid' },
  hammer: { component: Hammer, label: 'Hammer' },
  hand: { component: Hand, label: 'Hand' },
  hardDrive: { component: HardDrive, label: 'Hard Drive' },
  hardHat: { component: HardHat, label: 'Hard Hat' },
  hash: { component: Hash, label: 'Hash' },
  haze: { component: Haze, label: 'Haze' },
  heading: { component: Heading, label: 'Heading' },
  heart: { component: Heart, label: 'Heart' },
  helpCircle: { component: HelpCircle, label: 'Help Circle' },
  highlighter: { component: Highlighter, label: 'Highlighter' },
  home: { component: Home, label: 'Home' },
  image: { component: Image, label: 'Image' },
  inbox: { component: Inbox, label: 'Inbox' },
  indent: { component: Indent, label: 'Indent' },
  info: { component: Info, label: 'Info' },
  instagram: { component: Instagram, label: 'Instagram' },
  italic: { component: Italic, label: 'Italic' },
  key: { component: Key, label: 'Key' },
  keyboard: { component: Keyboard, label: 'Keyboard' },
  landmark: { component: Landmark, label: 'Landmark' },
  languages: { component: Languages, label: 'Languages' },
  laptop: { component: Laptop, label: 'Laptop' },
  lasso: { component: Lasso, label: 'Lasso' },
  laugh: { component: Laugh, label: 'Laugh' },
  layers: { component: Layers, label: 'Layers' },
  layout: { component: Layout, label: 'Layout' },
  layoutDashboard: { component: LayoutDashboard, label: 'Layout Dashboard' },
  layoutGrid: { component: LayoutGrid, label: 'Layout Grid' },
  layoutList: { component: LayoutList, label: 'Layout List' },
  lifeBuoy: { component: LifeBuoy, label: 'Life Buoy' },
  lightbulb: { component: Lightbulb, label: 'Lightbulb' },
  link: { component: Link, label: 'Link' },
  linkedin: { component: Linkedin, label: 'Linkedin' },
  list: { component: List, label: 'List' },
  listChecks: { component: ListChecks, label: 'List Checks' },
  listEnd: { component: ListEnd, label: 'List End' },
  listMinus: { component: ListMinus, label: 'List Minus' },
  listMusic: { component: ListMusic, label: 'List Music' },
  listOrdered: { component: ListOrdered, label: 'List Ordered' },
  listPlus: { component: ListPlus, label: 'List Plus' },
  listStart: { component: ListStart, label: 'List Start' },
  listVideo: { component: ListVideo, label: 'List Video' },
  listX: { component: ListX, label: 'List X' },
  loader: { component: Loader, label: 'Loader' },
  lock: { component: Lock, label: 'Lock' },
  logIn: { component: LogIn, label: 'Log In' },
  logOut: { component: LogOut, label: 'Log Out' },
  mail: { component: Mail, label: 'Mail' },
  map: { component: Map, label: 'Map' },
  mapPin: { component: MapPin, label: 'Map Pin' },
  maximize: { component: Maximize, label: 'Maximize' },
  menu: { component: Menu, label: 'Menu' },
  messageCircle: { component: MessageCircle, label: 'Message Circle' },
  messageSquare: { component: MessageSquare, label: 'Message Square' },
  mic: { component: Mic, label: 'Mic' },
  mic2: { component: Mic2, label: 'Mic 2' },
  minus: { component: Minus, label: 'Minus' },
  monitor: { component: Monitor, label: 'Monitor' },
  moon: { component: Moon, label: 'Moon' },
  moreHorizontal: { component: MoreHorizontal, label: 'More Horizontal' },
  moreVertical: { component: MoreVertical, label: 'More Vertical' },
  mousePointer: { component: MousePointer, label: 'Mouse Pointer' },
  move: { component: Move, label: 'Move' },
  music: { component: Music, label: 'Music' },
  navigation: { component: Navigation, label: 'Navigation' },
  newspaper: { component: Newspaper, label: 'Newspaper' },
  package: { component: Package, label: 'Package' },
  paintbrush: { component: Paintbrush, label: 'Paintbrush' },
  palette: { component: Palette, label: 'Palette' },
  paperclip: { component: Paperclip, label: 'Paperclip' },
  parkingCircle: { component: ParkingCircle, label: 'Parking Circle' },
  pause: { component: Pause, label: 'Pause' },
  pen: { component: Pen, label: 'Pen' },
  pencil: { component: Pencil, label: 'Pencil' },
  percent: { component: Percent, label: 'Percent' },
  personStanding: { component: PersonStanding, label: 'Person Standing' },
  phone: { component: Phone, label: 'Phone' },
  pictureInPicture: { component: PictureInPicture, label: 'Picture In Picture' },
  pieChart: { component: PieChart, label: 'Pie Chart' },
  pilcrow: { component: Pilcrow, label: 'Pilcrow' },
  pin: { component: Pin, label: 'Pin' },
  play: { component: Play, label: 'Play' },
  plug: { component: Plug, label: 'Plug' },
  plus: { component: Plus, label: 'Plus' },
  pocket: { component: Pocket, label: 'Pocket' },
  podcast: { component: Podcast, label: 'Podcast' },
  pointer: { component: Pointer, label: 'Pointer' },
  power: { component: Power, label: 'Power' },
  printer: { component: Printer, label: 'Printer' },
  qrCode: { component: QrCode, label: 'Qr Code' },
  quote: { component: Quote, label: 'Quote' },
  redo: { component: Redo, label: 'Redo' },
  refreshCcw: { component: RefreshCcw, label: 'Refresh Ccw' },
  refreshCw: { component: RefreshCw, label: 'Refresh Cw' },
  reply: { component: Reply, label: 'Reply' },
  rocket: { component: Rocket, label: 'Rocket' },
  rotateCcw: { component: RotateCcw, label: 'Rotate Ccw' },
  rotateCw: { component: RotateCw, label: 'Rotate Cw' },
  rss: { component: Rss, label: 'Rss' },
  ruler: { component: Ruler, label: 'Ruler' },
  save: { component: Save, label: 'Save' },
  scale: { component: Scale, label: 'Scale' },
  scissors: { component: Scissors, label: 'Scissors' },
  screenShare: { component: ScreenShare, label: 'Screen Share' },
  search: { component: Search, label: 'Search' },
  send: { component: Send, label: 'Send' },
  separatorHorizontal: { component: SeparatorHorizontal, label: 'Separator Horizontal' },
  server: { component: Server, label: 'Server' },
  settings: { component: Settings, label: 'Settings' },
  settings2: { component: Settings2, label: 'Settings 2' },
  share: { component: Share, label: 'Share' },
  share2: { component: Share2, label: 'Share 2' },
  sheet: { component: Sheet, label: 'Sheet' },
  shield: { component: Shield, label: 'Shield' },
  shieldCheck: { component: ShieldCheck, label: 'Shield Check' },
  shieldClose: { component: ShieldClose, label: 'Shield Close' },
  shieldOff: { component: ShieldOff, label: 'Shield Off' },
  shirt: { component: Shirt, label: 'Shirt' },
  shoppingBag: { component: ShoppingBag, label: 'Shopping Bag' },
  shoppingCart: { component: ShoppingCart, label: 'Shopping Cart' },
  siren: { component: Siren, label: 'Siren' },
  slash: { component: Slash, label: 'Slash' },
  slice: { component: Slice, label: 'Slice' },
  smartphone: { component: Smartphone, label: 'Smartphone' },
  smile: { component: Smile, label: 'Smile' },
  speaker: { component: Speaker, label: 'Speaker' },
  star: { component: Star, label: 'Star' },
  strikethrough: { component: Strikethrough, label: 'Strikethrough' },
  sun: { component: Sun, label: 'Sun' },
  sunrise: { component: Sunrise, label: 'Sunrise' },
  sunset: { component: Sunset, label: 'Sunset' },
  tablet: { component: Tablet, label: 'Tablet' },
  tag: { component: Tag, label: 'Tag' },
  target: { component: Target, label: 'Target' },
  tent: { component: Tent, label: 'Tent' },
  terminal: { component: Terminal, label: 'Terminal' },
  thumbsDown: { component: ThumbsDown, label: 'Thumbs Down' },
  thumbsUp: { component: ThumbsUp, label: 'Thumbs Up' },
  toggleLeft: { component: ToggleLeft, label: 'Toggle Left' },
  toggleRight: { component: ToggleRight, label: 'Toggle Right' },
  tool: { component: Tool, label: 'Tool' },
  trash: { component: Trash, label: 'Trash' },
  trash2: { component: Trash2, label: 'Trash 2' },
  trendingDown: { component: TrendingDown, label: 'Trending Down' },
  trendingUp: { component: TrendingUp, label: 'Trending Up' },
  triangle: { component: Triangle, label: 'Triangle' },
  truck: { component: Truck, label: 'Truck' },
  tv: { component: Tv, label: 'Tv' },
  twitch: { component: Twitch, label: 'Twitch' },
  twitter: { component: Twitter, label: 'Twitter' },
  type: { component: Type, label: 'Type' },
  underline: { component: Underline, label: 'Underline' },
  undo: { component: Undo, label: 'Undo' },
  unfoldHorizontal: { component: UnfoldHorizontal, label: 'Unfold Horizontal' },
  unfoldVertical: { component: UnfoldVertical, label: 'Unfold Vertical' },
  unlink: { component: Unlink, label: 'Unlink' },
  upload: { component: Upload, label: 'Upload' },
  user: { component: User, label: 'User' },
  userCheck: { component: UserCheck, label: 'User Check' },
  userCog: { component: UserCog, label: 'User Cog' },
  userMinus: { component: UserMinus, label: 'User Minus' },
  userPlus: { component: UserPlus, label: 'User Plus' },
  userX: { component: UserX, label: 'User X' },
  users: { component: Users, label: 'Users' },
  video: { component: Video, label: 'Video' },
  voicemail: { component: Voicemail, label: 'Voicemail' },
  volume: { component: Volume, label: 'Volume' },
  volume1: { component: Volume1, label: 'Volume 1' },
  volume2: { component: Volume2, label: 'Volume 2' },
  volumeX: { component: VolumeX, label: 'Volume X' },
  wallet: { component: Wallet, label: 'Wallet' },
  watch: { component: Watch, label: 'Watch' },
  webcam: { component: Webcam, label: 'Webcam' },
  wifi: { component: Wifi, label: 'Wifi' },
  wind: { component: Wind, label: 'Wind' },
  workflow: { component: Workflow, label: 'Workflow' },
  wrapText: { component: WrapText, label: 'Wrap Text' },
  x: { component: X, label: 'X' },
  youtube: { component: Youtube, label: 'Youtube' },
  zap: { component: Zap, label: 'Zap' },
  ...ctaIconsMap,
};

export const featureIconsMap: Record<string, IconDefinition> = allIconsMap;

    